### ISSUE TITLE
Wrong link to Maven Repository

### ISSUE THREAD

**Issue by mkarg** [pgjdbc/www#11]
jdbc.postgresql.org points to http://mvnrepository.com/artifact/org.postgresql which is wrong, as this is NOT the central maven repository. Instead it must certainly point to http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.postgresql%22%20AND%20a%3A%22postgresql%22 which not only IS the central maven repository, but moreover direclty lists all available versions of pgjdbc.

**Comment by davecramer** [comment]
fixed
