### ISSUE TITLE
Public API Documentation URL returns 404 HTTP error

### ISSUE THREAD

**Issue by zloster** [pgjdbc/www#24]
Currently the URL https://jdbc.postgresql.org/documentation/publicapi/index.html does not display the Javadoc API documentation.
I think this happened after the recent release of the new JDBC driver revision.

**Comment by davecramer** [comment]
ha. I guess my idea of rm -rf old wasn't such a good one ;)

ls publicapi -al
lrwxrwxrwx 1 davec davec 33 Sep 11  2013 publicapi ->
../../old/documentation/publicapi

Thanks for the report

Dave Cramer

**Comment by davecramer** [comment]
Fixed ...

Thanks again

Dave Cramer

**Comment by zloster** [comment]
Looks good. Cheers.
